name: Scan Container Image Periodically

on:
  workflow_dispatch:
  schedule:
    - cron: '38 8 * * 6'

jobs:
  scan_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull latest 3.x.y Image
        run: podman pull ghcr.io/${{ github.repository_owner }}/alpine-wget:3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@4b9b6fb4ef28b31450391a93ade098bb00de584e # tag=0.3.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/alpine-wget:3
          vuln-type: os
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@27ea8f8fe5977c00f5b37e076ab846c5bd783b96 # tag=v2
        with:
          sarif_file: trivy-results.sarif
