name: Scan Container Image Periodically

on:
  workflow_dispatch:
  schedule:
    - cron: '38 8 * * 6'

jobs:
  scan_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull latest 3.x.y Image
        run: podman pull ghcr.io/${{ github.repository_owner }}/alpine-wget:3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac # tag=0.7.1
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/alpine-wget:3
          vuln-type: os
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@807578363a7869ca324a79039e6db9c843e0e100 # tag=v2.1.27
        with:
          sarif_file: trivy-results.sarif
