name: Scan Container Image Periodically

on:
  workflow_dispatch:
  schedule:
    - cron: '38 8 * * 6'

permissions:
  contents: read
  security-events: write # required for github/codeql-action/upload-sarif

jobs:
  scan_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull latest 3.x.y Image
        run: podman pull ghcr.io/${{ github.repository_owner }}/alpine-wget:3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # tag=0.8.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/alpine-wget:3
          vuln-type: os
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@436dbd9100756e97f42f45da571adeebf8270723 # v2.2.0
        with:
          sarif_file: trivy-results.sarif
