name: Build and Publish Image

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Install qemu dependency
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Container Metadata
        id: container-metadata
        uses: docker/metadata-action@v3.8.0
        with:
          images: |-
            alpine-wget
          tags: |-
            type=edge
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}

      # Workaround since docker/metadata-action tags force the image names to be included
      # which in turn blocks the redhat-actions/push-to-registry action to work with the registry setting
      - name: Setup Variables
        run: |-
          TAG=${GITHUB_REF#refs/tags/}
          echo "MAJOR=${TAG%%.*}" >> $GITHUB_ENV
          echo "MAJOR_MINOR=${TAG%.*}" >> $GITHUB_ENV
          echo "SEMVER=${TAG}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.9
        with:
          image: alpine-wget
          tags: latest ${{ env.MAJOR }} ${{ env.MAJOR_MINOR }} ${{ env.SEMVER }} sha-${{ env.SHORT_SHA }}
          labels: ${{ steps.container-metadata.outputs.labels }}
          oci: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          containerfiles: ./Containerfile

      - name: Publish Image to ghcr.io
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Publish Image to quay.io
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/k3rnel-pan1c
          username: k3rnel-pan1c+github_actions
          password: ${{ secrets.RH_TOKEN }}

      - name: Publish Image to docker.io
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/k3rnelpan1c
          username: k3rnelpan1c
          password: ${{ secrets.DH_TOKEN }}
