name: Build and Publish Image

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Install qemu dependency
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Container Metadata
        id: container-metadata
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # tag=v4.1.1
        with:
          images: |-
            alpine-wget
          tags: |-
            type=edge
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}

      # Workaround since docker/metadata-action tags force the image names to be included
      # which in turn blocks the redhat-actions/push-to-registry action to work with the registry setting
      - name: Setup Variables
        run: |-
          TAG=${GITHUB_REF#refs/tags/}
          echo "MAJOR=${TAG%%.*}" >> $GITHUB_ENV
          echo "MAJOR_MINOR=${TAG%.*}" >> $GITHUB_ENV
          echo "SEMVER=${TAG}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@d097e2e3d2a45b68a7c09040e3de33427bab66af # tag=v2.10
        with:
          image: alpine-wget
          tags: latest ${{ env.MAJOR }} ${{ env.MAJOR_MINOR }} ${{ env.SEMVER }} sha-${{ env.SHORT_SHA }}
          labels: ${{ steps.container-metadata.outputs.labels }}
          oci: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          containerfiles: ./Containerfile

      - name: Publish Image to ghcr.io
        uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # tag=v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Publish Image to quay.io
        uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # tag=v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/k3rnel-pan1c
          username: k3rnel-pan1c+github_actions
          password: ${{ secrets.RH_TOKEN }}

      - name: Publish Image to docker.io
        uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # tag=v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/k3rnelpan1c
          username: k3rnelpan1c
          password: ${{ secrets.DH_TOKEN }}
